browser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('terminals/new', views.terminals_new),
    path('terminals/<uuid:terminal_id>/edit', views.terminals_edit),
    path('terminals/<uuid:terminal_id>', views.terminals_page),
    path('terminals', views.terminals_all),
    path('states/<str:state_id>', views.states_page),
    path('states', views.states_all),
    path('about', views.about_page),
    path('chatbot', views.chatbot_page),
]

travelinfo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('browser.urls')),
    path('resolve/', include('resolver.urls')),
]

browser/models.py
from django.db import models

import uuid

class State(models.Model):
    name = models.CharField(max_length=150)
    state_id = models.CharField(max_length=16, blank=True)

    def __str__(self):
        return self.name

class Terminal(models.Model):
    name = models.CharField(max_length=300)
    terminal_id = models.UUIDField(default=uuid.uuid4, null=True)
    AIR = "air"
    ROAD = "road"
    RAIL = "rail"
    SUPPORTED_MODES = (
        (AIR, 'Air'),
        (ROAD, 'Road'),
        (RAIL, 'Rail')
    )
    mode = models.CharField(max_length=12, choices=SUPPORTED_MODES)
    state = models.ForeignKey('State', on_delete=models.PROTECT)
    # set to protect cause states should not be deleted easily
    description = models.TextField()
    dest_terminals = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return f"{self.name} - {self.state}"

browser/forms.py
from django import forms

from .models import State, Terminal


def get_list_of_states():
    ALL_STATES = [(state.state_id, state.name) for state in State.objects.all()]
    return ALL_STATES

def get_supported_modes():
    AIR = "air"
    ROAD = "road"
    RAIL = "rail"
    SUPPORTED_MODES = (
        (AIR, 'Air'),
        (ROAD, 'Road'),
        (RAIL, 'Rail')
    )
    return SUPPORTED_MODES

def get_dest_terminals():
    ALL_TERMINALS = [(terminal.terminal_id, terminal.name) for terminal in Terminal.objects.all()]
    return ALL_TERMINALS

class TerminalForm(forms.Form):
    name = forms.CharField(label="Terminal's name",
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )
    mode = forms.ChoiceField(choices=get_supported_modes)
    state = forms.ChoiceField(choices=get_list_of_states)
    description = forms.CharField(widget=forms.Textarea, help_text="Describe the physical characteristics of the terminal, plus how to get there.")
    dest_terminals = forms.MultipleChoiceField(choices=get_dest_terminals, label="Destination terminals", required=False)

browser/views.py
import random, string

from django.http import HttpResponseRedirect
from django.shortcuts import render

import requests
from environs import Env

from .forms import TerminalForm
from .models import Terminal, State


env = Env()
env.read_env()


def index(request):
    states = State.objects.all()
    states = sorted(states, key=lambda s: s.terminal_set.count(), reverse=True)
    terminals = Terminal.objects.all()

    context = {'terminals': terminals[:16], 'states': states[:12]}
    return render(request, 'browser/index.html', context)

def terminals_new(request):
    if request.method == 'POST':
        form = TerminalForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            terminal = Terminal()
            terminal.save()
            try:
                terminal.name = data['name']
                terminal.mode = data['mode']
                terminal.description = data['description']
                terminal.state = State.objects.get(state_id=data['state'])

                dest_terminals = [Terminal.objects.get(terminal_id=terminal_id) for terminal_id in data['dest_terminals']]
                for dest_terminal in dest_terminals:
                    terminal.dest_terminals.add(dest_terminal)
                
                terminal.save()
                return HttpResponseRedirect('/')
            except:
                # ensure incomplete records are not written to db
                terminal.delete()
    else:
        form = TerminalForm()

    return render(request, 'browser/terminals_new.html', {'form': form})

def terminals_edit(request, terminal_id):
    terminal = Terminal.objects.get(terminal_id=terminal_id)

    if request.method == 'POST':
        form = TerminalForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            terminal.name = data['name']
            terminal.mode = data['mode']
            terminal.description = data['description']
            terminal.state = State.objects.get(state_id=data['state'])

            terminal.dest_terminals.clear() # avoid incremental addition
            dest_terminals = [Terminal.objects.get(terminal_id=terminal_id) for terminal_id in data['dest_terminals']]
            for dest_terminal in dest_terminals:
                terminal.dest_terminals.add(dest_terminal)
            
            terminal.save()
            return HttpResponseRedirect(f'/terminals/{terminal_id}')
    else:
        existing_data = {
            'name': terminal.name,
            'mode': terminal.mode,
            'state': terminal.state.state_id,
            'description': terminal.description,
            'dest_terminals': [dest_terminal.terminal_id for dest_terminal in terminal.dest_terminals.all()]
        }
        form = TerminalForm(initial=existing_data)
    
    context = {'terminal': terminal, 'form': form}
    return render(request, 'browser/terminals_edit.html', context)

def terminals_all(request):
    terminals = Terminal.objects.all()

    context = {'terminals': terminals}
    return render(request, 'browser/terminals_all.html', context)

def terminals_page(request, terminal_id):
    terminal = Terminal.objects.get(terminal_id=terminal_id)

    context = {'terminal': terminal}
    return render(request, 'browser/terminals_page.html', context)

def states_all(request):
    states = State.objects.all()

    context = {'states': states}
    return render(request, 'browser/states_all.html', context)

def states_page(request, state_id):
    state = State.objects.get(state_id=state_id)

    context = {'state': state}
    return render(request, 'browser/states_page.html', context)

def about_page(request):
    return render(request, 'browser/about_page.html')

def random_user_id():
    pool = string.ascii_letters + string.digits
    return "".join(random.choices(pool, k=64))

def chatbot_page(request):
    # get direct line token
    headers={"Authorization": f"Bearer {env.str('AZ_DIRECT_LINE_SECRET')}"}
    data = {
            "user": {
                "id": random_user_id(), # ensure generation of new tokens
                "name": "Interstate Traveller"
            },
            "trustedOrigins": env.list('AZ_CHATBOT_TRUSTED_ORIGINS')
        }
    resp = requests.post(
        "https://directline.botframework.com/v3/directline/tokens/generate",
        headers=headers,
        data=data
    )
    payload = resp.json()
    context = {
            'direct_line_token': payload['token'],
            'user_id': data['user']['id'],
            'username': data['user']['name'],
            'under_construction': True
        }
    return render(request, 'browser/chatbot.html', context)

browser/templates/browser/about_page.html
{% extends "browser/base.html" %}

    {% block page_content %}

    <h4>General Information</h4>
    <p>TravelInfo was built to help the traveller know where public transport terminals are in each state. And which destination you can travel to from a terminal.</p>
    <p>For example, TravelInfo can tell you that there are X number of interstate terminals in Lagos State, and if you want to get a bus going to Kaduna, you need to go to Terminal XYZ.</p>
    <p>That is what TravelInfo does.</p>
    <p>You can get this information via the <a href="/chatbot">chatbot</a>.</p>

    <h4>Data entry</h4>
    <p>This part of the application you are on is the Data Entry part.</p>
    <p>TravelInfo relies on contributors to tell us knowledge of terminals they've visted and states they've travelled to.</p>
    <p>So please, go ahead to <a href="/terminals/new">add new terminals</a>, or update information on already added terminals. You can edit the description of how to get to that terminal, or if a connected state/terminal has not been added, you can do that.</p>

    <h5>GitHub and contribution</h5>
    <p>TravelInfo is being built in the open and welcomes your contribution.</p>
    <p>This app's repo is here: <a href="https://github.com/wrecodde/travelinfo-app" target="_blank">wrecodde/travelinfo-app</a></p>
    {% endblock %}
    

browser/templates/browser/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TravelInfo Browser</title>

    <link rel="stylesheet" href="https://taniarascia.github.io/primitive/css/main.css">
    <style>
        .hide-on-small {
            display:block;
        }
        /* width > 768px */
        @media screen and (max-width: 768px){ 
            .hide-on-small{
                display:none;
            }
        }
        /* width < 768px */
        @media screen and (min-width: 768px){ 
            .hide-on-small{
                display:flex;
            }
        }
    </style>
</head>
<body>
    <div class="small-container">
        <div id="nav">
            <div class="flex-row">
                <div class="flex-small">
                    <h3><a href="/">TravelInfo</a></h3>
                </div>
                <div class="flex-small vertical-center hide-on-small">
                    <p>
                        <a href="/terminals/new">Add new terminal</a> - 
                        <a href="/terminals">All terminals</a> - 
                        <a href="/states">All states</a>
                    </p>
                </div>
            </div>
        </div>
        
        {% block page_content %}
        {% endblock %}
    </div>
</body>
</html>

browser/templates/browser/chatbot.html
{% extends "browser/base.html" %}

    {% block page_content %}
    {% if under_construction %}
      <h4>Chatbot is under construction</h4>
      <p>Do check back!</p>
    {% else %}
      <p>The chatbot currently fulfills a single type of query, where you specify the origin state and destination state. Examples listed below:</p>
      <ul>
         <li>from <b>lagos</b> state to <b>ondo</b> state </li>
         <li><b>fct</b> to <b>abia</b> state</li>
         <li>bus from <b>plateau</b> state to <b>ogun</b> state</li>
      </ul>
      <hr/><br/><br/>
      <div id="webchat" role="main"></div>
      <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
      <script>

         // Set style options.
         const styleOptions = {
            botAvatarInitials: 'TB',
            userAvatarInitials: 'IT'
         };

         window.WebChat.renderWebChat(
            {
               directLine: window.WebChat.createDirectLine({
                  token: "{{ direct_line_token }}"
               }),
               userID: "{{ user_id}}",
               username: "{{ username }}",
               locale: 'en-US',
               styleOptions
            },
            document.getElementById('webchat')
         );
      </script>
   {% endif %}
   {% endblock %}

browser/templates/browser/index.html
{% extends "browser/base.html" %}
    {% block page_content %}
        <p>Information on Nigerian interstate public transport</p>
        <p>As a traveller, whenever you need to travel to another state and do not know where (which park/terminal) to get a bus to your destination, you can consult this application. <a href="/about">More about the app..</a></p>
        <p>Go ahead and add terminals (garages/parks) that you know have interstate buses</p>
        <a href="/terminals/new">Add new terminal</a> - 
        <a href="/terminals">All terminals</a> - 
        <a href="/chatbot"><b>Open Chatbot</b></a>

        <div class="flex-row">
            <div class="flex-small">
                <h4>Terminals</h4>
                {% if not terminals %}
                    <p>No terminals have been added yet</p>
                {% else %}
                <ul>
                    {% for terminal in terminals %}
                    <li>
                        <a href="/terminals/{{terminal.terminal_id}}">{{terminal}}</a>
                    </li>
                    {% endfor %}
                    {% if terminals|length >= 16 %}
                    <li><a href="/terminals">..and more</a></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>

            <div class="flex-small">
                <h4>States</h4>
                <ul>
                    {% for state in states %}
                        <li>
                            <a href="/states/{{state.state_id}}">{{state}} - {{state.terminal_set.count}} Terminal(s)</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endblock %}

browser/templates/browser/states_all.html
{% extends "browser/base.html" %}
    {% block page_content %}
        <h4>All States</h4>
        {% for state in states %}
        <p><a href="/states/{{state.state_id}}">{{state.name}}</a> has {{state.terminal_set.count}} terminal(s)</p>
        {% endfor %}
    {% endblock %}

browser/templates/browser/states_page.html
{% extends "browser/base.html" %}
    {% block page_content %}
        <h4>Travel Info on {{state.name}}</h4>

        <p>{{state.name}} has {{state.terminal_set.count}} terminal(s)</p>
        <div class="flex-row">
            <div class="flex-small">
                <h5>Terminals in state</h5>
                {% if state.terminal_set.count > 0 %}
                <ul>
                    {% for terminal in state.terminal_set.all %}
                        <li><a href="/terminals/{{terminal.terminal_id}}">{{terminal.name}}</a></li>
                    {% endfor %}
                </ul>
                {% else %}
                <p>There are no terminals in this state yet</p>
                {% endif %}
            </div>

            <div class="flex-small">
                <h5>Destination terminals</h5>
                <p>In a bit, we would aggregate info and tell you the states and terminals you can travel to from here</p>
            </div>
        </div>
    {% endblock %}

browser/templates/browser/terminals_all.html
{% extends "browser/base.html" %}
    {% block page_content %}
        <h4>All Terminals</h4>
        <a href="/terminals/new">Add new terminal</a>
        {% if not terminals %}
        <p>No terminals have been added yet</p>
        {% else %}
            <ul>
                {% for terminal in terminals %}
                <li>
                    <a href="/terminals/{{terminal.terminal_id}}">{{terminal.name}} in {{terminal.state}}</a>
                    <p>{{terminal.description}}</p>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endblock %}

browser/templates/browser/terminals_edit.html
{% extends "browser/base.html" %}
    {% block page_content %}
        <h4>Edit a terminal</h4>

        <div class="flex-row">
            <div class="flex-small">
                <form action="/terminals/{{terminal.terminal_id}}/edit" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Edit terminal">
                </form>
            </div>
        </div>
    {% endblock %}

browser/templates/browser/terminals_new.html
{% extends "browser/base.html" %}
    {% block page_content %}
        <h4>Add a new terminal</h4>

        <div class="flex-row">
            <div class="flex-small">
                <form action="/terminals/new" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Add terminal">
                </form>
            </div>
        </div>
    {% endblock %}

browser/templates/browser/terminals_page.html
{% extends "browser/base.html" %}
    {% block page_content %}
        <h4>{{terminal.name}}</h4>
        <p>
            <a href="/terminals/{{terminal.terminal_id}}/edit">Edit terminal</a>
        </p>

        <div class="flex-row">
            <div class="flex-small">
                <p>Terminal is in <a href="/states/{{terminal.state.state_id}}">{{terminal.state}}</a></p>
                <p><b>Transport Mode:</b> {{terminal.get_mode_display}}</p>
                <b>Terminal description:</b>
                <p>{{terminal.description | linebreaks}}</p>
            </div>

            <div class="flex-small">
                <h5>Destination terminals</h5>
                <p>This terminal connects to the following terminals:</p>
                {% if terminal.dest_terminals.count == 0 %}
                <p>No destination terminals yet</p>
                {% else %}
                    <ul>
                    {% for dest_terminal in terminal.dest_terminals.all %}
                        <li><a href="/terminals/{{dest_terminal.terminal_id}}">{{dest_terminal.name}}</a></li>
                    {% endfor %}
                    </ul>
                {%endif %}
            </div>
        </div>
    {% endblock %}